### ISSUE TITLE
Small change needed in python code

### ISSUE THREAD

**Issue by kcwcc** [ControlEverythingCommunity/HIH6020#1]
According to the Honeywell Technical Note on the  Humidicon family of sensors, to initiate a measurement, you need to issue a Measurement Request command prior to reading the sensor data.
This can be easily accomplished by adding in these lines prior to reading the data:

bus.write_quick(0x27)
time.sleep(0.1)

technically the conversion only takes a maximum of 70ms, so you can reduce the delay to 70 if you wish
This code was confirmed to work on the HIH8xxx series of sensor but the protocol should be the same.

**Comment by zaphod-42** [comment]
Thank you, I've added your fix
